<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>天津跨境贸易电子商务综合服务平台</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <!-- stylesheets -->	
    <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen" />
    <link id="color" rel="stylesheet" type="text/css" href="/css/colors/blue.css" />
	<link rel="stylesheet" type="text/css" href="/css/pagination.css" />
	<link type="text/css" href="/css/alterBgColor.css" rel="stylesheet" />		
	<link type="text/css" href="/css/smoothness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
	<link rel="stylesheet" href="/css/tip-yellow/tip-yellow.css" type="text/css" />
	<link rel="stylesheet" href="/css/tip-yellowsimple/tip-yellowsimple.css" type="text/css" />
    <!-- scripts (jquery) -->
    <script src="/js/jquery-1.8.3.min.js" type="text/javascript"></script>
    
    <!--<script src="/js/jquery-ui-1.8.custom.min.js" type="text/javascript"></script>-->
    <!--<script src="/js/jquery.ui.selectmenu.js" type="text/javascript"></script>-->
    <!--<script src="/js/jquery.flot.min.js" type="text/javascript"></script>-->
    <script src="/js/tiny_mce/tiny_mce.js" type="text/javascript"></script>
    <script src="/js/tiny_mce/jquery.tinymce.js" type="text/javascript"></script>
	<script src="/js/jquery-cookie.js" type="text/javascript"></script>
	<!--<script src="/js/switchToAdvancedSearch.js" type="text/javascript"></script>-->
	<script src="/js/jquery.poshytip.js" type="text/javascript"></script>
	<script src="/js/jquery.myframe.js" type="text/javascript"></script>
	<script src="/js/jquery.mytip.js" type="text/javascript"></script>
	<!--[if lte IE 6]>
	<script src="/js/DD_belatedPNG_0.0.8a-min.js" type="text/javascript"></script>
    <script type="text/javascript">
        DD_belatedPNG.fix('img');		
    </script>
	<![endif]-->
	
	<!--[if lte IE 6]>
	<link type="text/css" href="/css/ie6.css" rel="stylesheet" />
	<script src="/js/ie6.js" type="text/javascript"></script>
	<![endif]-->
	
	<!--[if gte IE 7]>
	<link type="text/css" href="/css/ie8.css" rel="stylesheet" />
	<![endif]-->
	
		
	
    <!-- scripts (custom) -->
    <script src="/js/smooth.js" type="text/javascript"></script>
    <script src="/js/smooth.menu.js" type="text/javascript"></script>
    <!--<script src="/js/smooth.chart.js" type="text/javascript"></script>-->
    <script src="/js/smooth.table.js" type="text/javascript"></script>
    <!--<script src="/js/smooth.form.js" type="text/javascript"></script>-->
    <!--<script src="/js/smooth.dialog.js" type="text/javascript"></script>-->
    <script src="/js/smooth.autocomplete.js" type="text/javascript"></script>
    <script src='/js/jquery-ui-1.9.2.custom.min.js' type="text/javascript"></script> 
	<!--<script src='/js/jquery-ui-1.9.2.custom.js' type="text/javascript"></script>-->
	
	<script src='/js/jquery.form.js' type="text/javascript"></script>
    <script src='/js/jquery.pagination.js' type="text/javascript"></script>
    <script src='/loadjs/loadjs/name/pagination' type="text/javascript"></script>
    
	<script src="/js/jquery.bgiframe.js" type="text/javascript"></script>
	<script src="/dwz/uploadify/scripts/jquery.uploadify.min.js" type="text/javascript"></script>
	
	<script src="/js/alterBgColor.js" type="text/javascript"></script>
	<!--<script src="/js/colResizable-1.3.min.js" type="text/javascript"></script> -->
	<?php echo $this->action("loadjs","loadjs",'default',array('name'=>'switchToAdvancedSearch'));?>
	<?php echo $this->action("loadjs","loadjs",'default',array('name'=>'main'));?>
	
    <script type="text/javascript">
	
        $(document).ready(function () {
		
			$('input[type=text]').placeholder();
			$('.tip').poshytip({className: 'tip-yellowsimple',
			showOn: 'focus',
			alignTo: 'target',
			alignX: 'right',
			alignY: 'center',
			offsetX: 5});		
		
            style_path = "/css/colors";

            $(".datepicker").datepicker({ dateFormat: "yy-mm-dd",showButtonPanel:true});
			$(".datepicker").attr('readonly',false);
			//$(".datepicker").val('0000-00-00');
			
			$(".datepicker").each(function(){
				 $(this).bind('blur',function(){
				 	if($(this).val()!='' &&!(/[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}$/.test($(this).val()))){
						alert('日期格式为：0000-00-00');
						$(this).focus();
					}
				 })
			});
			
						
            $("#box-tabs, #box-left-tabs").tabs();
            $.datepicker.setDefaults({ showButtonPanel: true, closeText: '清除', beforeShow: function (input, inst) { datepicker_CurrentInput = input; } });
            $(".ui-datepicker-close").live("click", function (){
                datepicker_CurrentInput.value = "";
            });			
			create_page_bar();
           
        });
		
		
		function create_page_bar()
		{
			
 			var total = $('.pagination').attr('totalcount');
			
			if($('.pagination').size()==0){ return;}
			
            var currencypage=$('.pagination').attr('currentpage');
            var pageSize = $('.pagination').attr('numperpage');
 

            var numrege = /[1-9]+[0-9]*/;
            if(!numrege.test(currencypage)){
                currencypage='1';
            }else{
                currencypage=currencypage-1;
            }
			
            var opt={
                current_page:currencypage,
                items_per_page:$('.pagination').attr('numperpage')
            }
			
            $(".pagination").pagination(total,opt);
			
            $('.pagination a').each(function(){
				//alert("bind");				
                  $(this).click(function(){
                      //处理首页和上一页
                      if($(this).hasClass('prev')){
                          //console.log($('.pagination a').filter('.prev'));
                          if($(this).html()=='首页'||$(this).html()=='Home'){
                              $('#page').val('1');
                          }else{
                              $('#page').val(currencypage);
                          }
                      }else if($(this).hasClass('last')){
                    	  var last = Math.ceil(total/pageSize)
                          $('#page').val(last);
                       }else if($(this).hasClass('next')){
                          if($('.pagination a').filter('.prev').last()[0]==this){						 
							  var last = Math.ceil(total/pageSize);
                              $('#page').val(last);
                          }else{
                              $('#page').val($('.current').html());
                          }
                      }else{
                          $('#page').val($(this).html());
                      } 
					
                      $('#pagerForm').submit();				
					 
					 
                  });
				  
				 
             });
		
		
		
		}//function create_page_bar()
		
		
		
        function pageselectCallback(page_index, jq){
            // Get number of elements per pagionation page from form
            var items_per_page =  $('.pagination').attr('numperpage');
            var total = $('.pagination').attr('totalcount');
            var max_elem = Math.min((page_index+1) * items_per_page, total);
            var newcontent = '';

            //window.location.href='/merchant/product?page='+$('.pagination').attr('currentpage');

            // Prevent click eventpropagation
            return false;
        }

        function getOptionsFromForm(){
            var opt = {callback: pageselectCallback};
            // Collect options from the text fields - the fields are named like their option counterparts
            $("input:text").each(function(){
                opt[this.name] = this.className.match(/numeric/) ? parseInt(this.value) : this.value;
            });
            // Avoid html injections in this demo
            var htmlspecialchars ={ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;"}
            $.each(htmlspecialchars, function(k,v){
                opt.prev_text = opt.prev_text.replace(k,v);
                opt.next_text = opt.next_text.replace(k,v);
            })
            return opt;
        }
		
		/*获取选择产品对话框的数据*/
		function getProductListBoxData(from,page,pageSize,sku,title,type){		   
			var from = from||'product';			
			var page = page||1;
			var pageSize = pageSize||20;
			var sku = sku||'';
			var title = title||'';
			var type = type||'';
			var areatext= $("textarea[name='sku_text']").val();	
			
			$.post('/merchant/product/repository',{from:from,page:page,pageSize:pageSize,sku:sku,title:title,type:type},function(result){
				$("#dialog").html(result);
			});
		
        }
      	function changeLang(lang){
			$.ajax({
				type:'POST',
				url:'/index/change-lang',
				data:{'langCode':lang},
				dataType:'json',
				success:function(json){
					if(json=='1'){
                        window.location.reload();
                    }
				}
			});
	    }
		
    </script>
	
</head>
<body>
	
    <?php echo $this->layout()->content;?>

<script>

		$(document).ready(function(){			
			resetIrameHeight();			
		});
		
		
	
</script>		
</body>
</html>