<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>天津跨境贸易电子商务综合服务平台</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <!-- stylesheets -->
    <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen" />
    <link id="color" rel="stylesheet" type="text/css" href="/css/colors/blue.css" />
	<!--<link rel="stylesheet" type="text/css" href="/css/pagination.css" />-->
	<!--<link type="text/css" href="/css/alterBgColor.css" rel="stylesheet" />-->
	<!--<link type="text/css" href="/css/smoothness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />-->
	<!--<link rel="stylesheet" href="/css/tip-yellow/tip-yellow.css" type="text/css" />-->
	<!--<link rel="stylesheet" href="/css/tip-yellowsimple/tip-yellowsimple.css" type="text/css" />-->
    <!-- scripts (jquery) -->
    <script src="/js/jquery-1.8.3.min.js" type="text/javascript"></script>

    <!--<script src="/js/jquery-ui-1.8.custom.min.js" type="text/javascript"></script>-->
    <!--<script src="/js/jquery.ui.selectmenu.js" type="text/javascript"></script>-->
    <!--<script src="/js/jquery.flot.min.js" type="text/javascript"></script>-->
    <!--<script src="/js/tiny_mce/tiny_mce.js" type="text/javascript"></script>-->
    <!--<script src="/js/tiny_mce/jquery.tinymce.js" type="text/javascript"></script>-->
	<script src="/js/jquery-cookie.js" type="text/javascript"></script>
	<!--<script src="/js/switchToAdvancedSearch.js" type="text/javascript"></script>-->
	<!--<script src="/js/jquery.poshytip.js" type="text/javascript"></script>-->
	<!--<script src="/js/jquery.myframe.js" type="text/javascript"></script>-->
	<!--[if lte IE 6]>
	<script src="/js/DD_belatedPNG_0.0.8a-min.js" type="text/javascript"></script>
    <script type="text/javascript">
        //DD_belatedPNG.fix('img');
    </script>
	<![endif]-->

	<!--[if lte IE 6]>
	<link type="text/css" href="/css/ie6.css" rel="stylesheet" />
	<script src="/js/ie6.js" type="text/javascript"></script>
	<![endif]-->

	<!--[if gte IE 7]>
	<link type="text/css" href="/css/ie8.css" rel="stylesheet" />
	<![endif]-->



    <!-- scripts (custom) -->
    <script src="/js/smooth.js" type="text/javascript"></script>
    <!--<script src="/js/smooth.menu.js" type="text/javascript"></script>-->
    <!--<script src="/js/smooth.chart.js" type="text/javascript"></script>-->
    <!--<script src="/js/smooth.table.js" type="text/javascript"></script>-->
    <!--<script src="/js/smooth.form.js" type="text/javascript"></script>-->
    <!--<script src="/js/smooth.dialog.js" type="text/javascript"></script>-->
    <!--<script src="/js/smooth.autocomplete.js" type="text/javascript"></script>-->
    <!--<script src='/js/jquery-ui-1.9.2.custom.min.js' type="text/javascript"></script> -->
	<!--<script src='/js/jquery-ui-1.9.2.custom.js' type="text/javascript"></script>-->

	<!--<script src='/js/jquery.form.js' type="text/javascript"></script>-->
    <!--<script src='/js/jquery.pagination.js' type="text/javascript"></script>-->
    <!--<script src='/loadjs/loadjs/name/pagination' type="text/javascript"></script>-->
    <!--<script src="/js/main.js" type="text/javascript"></script>-->
	<!--<script src="/js/jquery.bgiframe.js" type="text/javascript"></script>-->
	<!--<script src="/dwz/uploadify/scripts/jquery.uploadify.min.js" type="text/javascript"></script>-->

	<!--<script src="/js/alterBgColor.js" type="text/javascript"></script>-->
	<!--<script src="/js/colResizable-1.3.min.js" type="text/javascript"></script>-->
	<?php echo $this->action("loadjs","loadjs",'default',array('name'=>'myframe'));?>
	<?php echo $this->action("loadjs","loadjs",'default',array('name'=>'switchToAdvancedSearch'));?>

    <link rel="stylesheet" href="/css/admin_custom.css"/>
	<script type="text/javascript">

      	function changeLang(lang){
			$.ajax({
				type:'POST',
				url:'/index/change-lang',
				data:{'langCode':lang},
				dataType:'json',
				success:function(json){
					if(json=='1'){
                        window.location.reload();
                    }
				}
			});
	    }

    </script>

</head>
<body>

<div class="manageContainer">
    <div class="manageHeaderContainer">
        <!-- 顶部-->
        <div class="topContainer">
            <div class="min_width clearfix">
                <p class="logo"></p>
                <p class="link">
                    <span>登录账号：</span><a href="javascript:"><?php echo $_SESSION['customerAuth']['data']['code']; echo $_SESSION['customerAuth']['data']['account_level']==1 ? '-'.$_SESSION['customerAuth']['data']['account_code'] : '';?></a>
                    <a href="javascript:" style="margin-left:20px">英文</a>
                    <a href="javascript:" style="margin-left:20px">修改密码</a>
                    <a href="/login/out" style="margin-left:20px">退出</a>
                </p>
            </div>
        </div>
        <!-- 头部菜单-->
        <div class="topMenuContainer" id="topMenuContainer">
            <ul id="menutablist">
                <li><a href="javascript:" class="active fixActive">首页</a></li>
            </ul>
        </div>
    </div>
</div>

<!-- header -->



<!-- end header -->
<!-- content -->
<div id="content">
<!-- end content / left -->
<div id="left">
<?php echo $this->action("left-menu","index","merchant");?>
</div>
<!-- end content / left -->
<!-- content / right -->

<div id="right" >

	<div class="box">

    <?php echo $this->layout()->content;?>


	</div>

	<div clear="clear"></div>
</div>
<!-- end content / right -->
	<div clear="clear"></div>
</div>
<!-- end content -->
<!-- footer -->


<div id="footer">
    <p>Copyright &copy; 2015 E跨境 All Right Reserved.</p>
</div>

<!-- end footert -->
</body>
</html>
