<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>天津跨境贸易电子商务综合服务平台</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <!-- stylesheets -->
    <link rel="stylesheet" type="text/css" href="/css/reset.css" />
    <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen" />
    <link id="color" rel="stylesheet" type="text/css" href="/css/colors/blue.css" />
    <!-- scripts (jquery) -->
    <script src="/js/jquery-1.4.2.min.js" type="text/javascript"></script>
    <!--[if IE]><script language="javascript" type="text/javascript" src="/js/scripts/excanvas.min.js"></script><![endif]-->
    <script src="/js/jquery-ui-1.8.custom.min.js" type="text/javascript"></script>
    <script src="/js/jquery.ui.selectmenu.js" type="text/javascript"></script>
    <!--<script src="/js/jquery.flot.min.js" type="text/javascript"></script>-->
    <script src="/js/tiny_mce/tiny_mce.js" type="text/javascript"></script>
    <script src="/js/tiny_mce/jquery.tinymce.js" type="text/javascript"></script>
    <!-- scripts (custom) -->
    <script src="/js/smooth.js" type="text/javascript"></script>
    <script src="/js/smooth.menu.js" type="text/javascript"></script>
    <script src="/js/smooth.chart.js" type="text/javascript"></script>
    <script src="/js/smooth.table.js" type="text/javascript"></script>
    <script src="/js/smooth.form.js" type="text/javascript"></script>
    <script src="/js/smooth.dialog.js" type="text/javascript"></script>
    <script src="/js/smooth.autocomplete.js" type="text/javascript"></script>
	<script src="/js/colResizable-1.3.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            style_path = "/css/colors";

            $("#date-picker").datepicker();

            $("#box-tabs, #box-left-tabs").tabs();
        });
    </script>
</head>
<body>

<!-- header -->
<div id="header">
    <!-- logo -->
    <div id="logo">
        <h1><a href="" title="Cargo OMS"><img src="/images/logo.png" alt="Cargo OMS" /></a></h1>
    </div>
    <!-- end logo -->
    <!-- user -->
    <ul id="user">
        <li class="first"><a href="">登陆账号：EC001</a></li>
        <li><a href="">Logout</a></li>
    </ul>
    <!-- end user -->
    <div id="header-inner">
        <div id="home">
            <a href="" title="Home"></a>
        </div>
        <!-- quick -->
        <ul id="quick">
            <li>
                <a href="#" title="Products"><span class="normal">帮助中心</span></a>
            </li>
            <li>
                <a href="#" title="Products"><span class="normal">条目2</span></a>
            </li>
        </ul>
        <!-- end quick -->
        <div class="corner tl"></div>
        <div class="corner tr"></div>
    </div>
</div>
<!-- end header -->
<!-- content -->
<div id="content">
<!-- end content / left -->
<div id="left">
    <div id="menu">
        <h6 id="h-menu-products" class="selected"><a href="#products"><span>产品管理</span></a></h6>
        <ul id="menu-products" class="opened">
            <li><a href="/merchant/product/add">产品新增</a></li>
            <li><a href="/merchant/product">产品列表</a></li>
        </ul>
        <h6 id="h-menu-pages"><a href="#pages"><span>入库管理</span></a></h6>
        <ul id="menu-pages" class="opened">
            <li><a href="/merchant/receiving/create">ASN新增</a></li>
            <li><a href="/merchant/receiving/list">ASN列表</a></li>
        </ul>
        <h6 id="h-menu-events"><a href="#events"><span>订单管理</span></a></h6>
        <ul id="menu-events" class="opened">
            <li><a href="/merchant/order/create">订单新增</a></li>
            <li class="last"><a href="/merchant/order">订单列表</a></li>
        </ul>
        <h6 id="h-menu-links"><a href="#links"><span>财务管理</span></a></h6>
        <ul id="menu-links" class="opened">
            <li><a href="">当前余额</a></li>
            <li><a href="">充值记录</a></li>
            <li class="last"><a href="">客户充值</a></li>
        </ul>
    </div>
</div>
<!-- end content / left -->
<!-- content / right -->
<div id="right">
<!-- table -->
<!--<div class="box">-->
    <?php echo $this->layout()->content;?>
<!--</div>-->

</div>
<!-- end content / right -->
</div>
<!-- end content -->
<!-- footer -->
<div id="footer">
    <p>Copyright &copy; 2013 <a href="http://www.cargofe.com" target="_blank">www.cargofe.com</a> All Right Reserved.</p>
</div>
<!-- end footert -->
</body>
</html>