<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" />
<title>天津跨境贸易电子商务综合服务平台</title>
<link href="/dwz/themes/default/main.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="/dwz/themes/default/style-self.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="/dwz/themes/default/style.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="/dwz/themes/css/core.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="/dwz/themes/css/print.css" rel="stylesheet" type="text/css" media="print"/>
<link href="/dwz/uploadify/css/uploadify.css" rel="stylesheet" type="text/css" media="screen"/>
<!--[if IE]>
<link href="/dwz/themes/css/ieHack.css" rel="stylesheet" type="text/css" media="screen"/>
<![endif]-->
<!--[if lte IE 9]>
<script src="/dwz/js/speedup.js" type="text/javascript"></script>
<![endif]-->
<script src="/dwz/js/jquery-1.7.2.js" type="text/javascript"></script>
<script src="/dwz/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/dwz/js/jquery.validate.js" type="text/javascript"></script>
<script src="/dwz/js/jquery.bgiframe.js" type="text/javascript"></script>
<script src="/dwz/uploadify/scripts/jquery.uploadify.js" type="text/javascript"></script>

<script src="/dwz/dwz.min.js" type="text/javascript"></script>

<script src="/dwz/js/dwz.navTab.js" type="text/javascript"></script>
<script src="/dwz/js/dwz.tab.js" type="text/javascript"></script>

<script src="/dwz/js/dwz.regional.zh.js" type="text/javascript"></script>
<script type="text/javascript">
$(function(){
	DWZ.init("/dwz/dwz.frag.xml", {
		debug:false,
		pageInfo:{pageNum:"page", numPerPage:"pageSize"},
		callback:function(){
			initEnv();
			$("#themeList").theme({themeBase:"dwz/themes"});
		}
	});
});
</script>
</head>
<body>
<?php echo $this->layout()->content;?>	
</body>